### ISSUE TITLE
Add a download button.

### ISSUE THREAD

**Issue by DogancanYr** [dvuzu/monkrus-search#1]
Can you add a direct download link from uniondht.org to the site?

**Comment by dvuzu** [comment]
It would take a long time to scrape and I don't want to ddos monkrus every 24 hours. I would need to go to every page and scrape for links. What i do right now is too much. I will see what I can do.

**Comment by DogancanYr** [comment]
You can search the site with this.
You can write the name directly. Only spaces need to be replaced with pluses.
https://uniondht.org/tracker.php?nm=Adobe+Photoshop+2024+(v25.7)+Multilingual
Then you get this from the site: < td id="2140633" class="row1 topic_id" >
And this way you create the link :https://uniondht.org/dl.php?t=2140633

**Comment by dvuzu** [comment]
The problem is that some of the old monkrus posts are not on uniondht.

I am right now running a scrape to see how much time it will take to scrape all of the monkrus links and how big scraped_data.json will get.

**Comment by dvuzu** [comment]
Also i could always add a link that goes to "https://uniondht.org/tracker.php?nm=" + title and warn the user before a redirect to check if its uploaded by monkrus.

Also, your way would take a long time and i would just get blocked by them sadly.

**Comment by dvuzu** [comment]
Okay, scraping is finished. Took me over 20 minutes (i am limited to 2000 minutes) while current one takes one minute. File is over 1mb. I will see what i can do. Thanks for the suggestion.

**Comment by dvuzu** [comment]
enjoy the update :)

**Comment by DogancanYr** [comment]
It's a small problem. When I click show link and refresh the page, it returns to its previous state, but it does not happen with the show posts without links.

**Comment by dvuzu** [comment]
fixed :)
